### ISSUE TITLE
Can this actually scrape a new site successfully and produce diffs? 

### ISSUE THREAD

**Issue by ezramechaber** [Digital44/newsdiffs-wh#1]
[ 1-2 day task ]

**Comment by ezramechaber** [comment]
This should scrape all pages on the main domain (and exclude subdomains, which are too active with user-generated content).

The MVP could just scrape the main issue pages, anything on /blog. I can provide a list if we need to do it that way.

**Comment by EricSchles** [comment]
I can do a scrape for some specific stuff. Might be best if put individual sites in a database and then pull from there, scraping each domain.  This way sites scraped don't have to live in the codebase.

**Comment by EricSchles** [comment]
This will live on the scrape branch with PRs into master

**Comment by ezramechaber** [comment]
Great, thanks @EricSchles. What's the best way to start creating that list of sites? Should we stick to just site sections with an RSS feed, or is anything fair game for the scraper?

**Comment by dkaoster** [comment]
Hey guys! Was going to reply in the email thread but decided that I would rather not spam everyone with yet another email. I'd love to help out with this effort in whatever way possible.

@ezramechaber It seems the scraper can work with any kind of html page, although I don't know how it behaves with javascript on pages. (but that probably shouldn't be a concern for whitehouse.gov)

**Comment by awong-dev** [comment]
@dkaoster the scraper uses beautifulsoup which is just a DOM processor, so it won't touch JS.

That being said, I expect most of these pages to be static content.

The bigger question is whether or not the scraper wrapper does any sort of crawling of the domain. I think that's something we can write in the code itself, but I haven't had time to try.

**Comment by awong-dev** [comment]
FYI, I was wrong about the lack of crawling. It does indeed seem to crawl to some extent. Running `python test_parser.py whitehouse.WhitehouseParser` with PR #8 will yield

```
https://www.whitehouse.gov/#content-start
https://www.whitehouse.gov/#block-menu-block-sixteenhundrednav-main
https://www.whitehouse.gov/contact
https://www.whitehouse.gov/
https://www.whitehouse.gov/#
https://www.whitehouse.gov/blog
https://www.whitehouse.gov/blog
https://www.whitehouse.gov/briefing-room/speeches-and-remarks
https://www.whitehouse.gov/briefing-room/press-briefings
https://www.whitehouse.gov/briefing-room/statements-and-releases
https://www.whitehouse.gov/briefing-room/presidential-actions
...
```

Something is wrong with the crawl logic though since it's double-printing `/blog` and, more critically, didn't crawl ANY of the articles under blog.

**Comment by awong-dev** [comment]
Okay, read through it for real now.  The code, as-is, ONLY crawls 1 link deep from the "feeder_url". It does not do a traditional crawl of the website meaning that it cannot really notice new sections.

It wouldn't be hard to add a recursive crawl, but that's an add on feature.

@ezramechaber Are there specific subsections of each domain that you know you want to focus on exclusively?  Or did you really just want "all changes"?  I assume you actually want "all changes"...

**Comment by ezramechaber** [comment]
Hey @awong-dev, got it! Long term I was thinking "all changes" but let's start with an MVP. I'll start putting together specific links we'd like this thing to use as a base (so that it crawls that + one deep). 

For a very straightforward MVP, let's use everything listed on https://www.whitehouse.gov/blog. Each item listed there is worth keeping an eye on. One note: Because of the WH's old data architecture and the way it's currently being listed, articles aren't getting standard slugs. Each "blog post" actually lives at https://www.whitehouse.gov/the-press-office/YEAR/MONTH/DAY/TITLE instead of /blog/....

**Comment by awong-dev** [comment]
I actually scrapped all of the first 2 levels... Look at the heroku
prototype before investing more energy :)

**Comment by ezramechaber** [comment]
@awong-dev Perfect, will do.

**Comment by ezramechaber** [comment]
@awong-dev Should I be able to see the actual diffs pages yet, or is that still a work in progress? I get an error page when I try to look at an actual comparison.

**Comment by awong-dev** [comment]
WIP. Something is wrong with the scraper.

**Comment by awong-dev** [comment]
Okay, so I think I know what's happening. The architecture of the original code is funky. It uses both a database AND a local-to-webserver git instance ( #12 ) to store the results of the scrape. The scraper dumps metadata into the database, but for some reason stores the article text in the git instance.  I think it's trying to save space by taking advantage of git's ability to (implicitly) do delta compression. This seems misguided.  Unfortunately, it also means heroku and most scalable webplatforms today will suddenly lose all bodies of the articles. What's happening is likely this:

(1) Scraper runs on a new instance of the machine with a new checkout
(2) Scraper dumps contents into a LOCAL FILESYSTEM version of git and updates the database.
(3) Scaper machine is killed at some point. All git history is lost.
(4) Webserver runs on a _different_ machine without the git instance
(5) All attempts to retrieve the article 404.

The "right" fix is likely to update the model so we store the actual article contents directly in the DB.  This is starting to move the project from 1-2 hack job to couple-day real engineering effort. 

@ezramechaber Tagging for an FYI to reset expectations on timelines.  We might want some more hands...in particular, people who know Django and python.

**Comment by ezramechaber** [comment]
Roger that, thanks @awong-dev. Let me know if you have anyone in mind, or if we should reach out to the Digital44 thread. Sorry this is becoming a bigger project than anticipated!
