### ISSUE TITLE
Transfer ownership to digital44 org?

### ISSUE THREAD

**Issue by awong-dev** [Digital44/newsdiffs-wh#13]
Hey @ezramechaber, would you feel okay transferring this to the digital44 org?  I think it might help us share some of the various admin bits when integration with any third party services we might use.

**Comment by ezramechaber** [comment]
Great, let's do it! You good to transfer @awong-dev or do you need me to initiate?

**Comment by awong-dev** [comment]
You're the owner so I think you have to do it.

**Comment by ezramechaber** [comment]
Done.
