### ISSUE TITLE
Automatic Deployment from this repo

### ISSUE THREAD

**Issue by awong-dev** [Digital44/newsdiffs-wh#7]
@ezramechaber Turns out that apparently Heroku won't let me connect to this github repo since it's owned by you.

Three solutions:
  1. I fork this repo and deploy from my copy [that's the current steup]
  2. We move this repo to some github organization if such a thing exists. That'd simplify permissions.
  3. I add you as a collaborator on heroku and see if that lets *you* connect the github repo.

If you have experience with Heroku, I'd love to try (3) from above.

**Comment by ezramechaber** [comment]
@awong-dev Sorry I missed this—yep, I've got some Heroku experience, happy to try to connect it!

**Comment by awong-dev** [comment]
@ezramechaber I'm trying to get Ross Dakin to add us to the digital44 org. Then we can use org permissions and not end up with this mess... but in the mean time, send me your heroku username and we'll see if we can make this work.

**Comment by ezramechaber** [comment]
@awong-dev Just my email address, thanks!

**Comment by awong-dev** [comment]
@ezramechaber added you as collaborator on https://dashboard.heroku.com/apps/newsdiffs-wh.  It sounds like you have your own deploy though.  I'd say we should stick with one, so either add me as a collaborator on yours and post the link back here, or log onto mine and try to modify the deploy so it talks to your repo.

**Comment by ezramechaber** [comment]
@awong-dev Yep, will use yours. Just got the confirmation + connected it to the master repo to auto-deploy.

**Comment by ezramechaber** [comment]
(sorry, will keep this open til we've officially migrated to an org)

**Comment by awong-dev** [comment]
Looks done enough to me. Org migration in #13
