### ISSUE TITLE
New branch for front end

### ISSUE THREAD

**Issue by ezramechaber** [Digital44/newsdiffs-wh#9]
Hey @awong-dev - created a new branch to make some front-end changes (changes to website folder only). When I tried to push to a new Heroku app to test it, I got the following error:

`     $ python website/manage.py collectstatic --noinput
       Unknown command: 'collectstatic'
       Type 'manage.py help' for usage.
 !     Error while running '$ python website/manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets`

Not sure what's up, so I didn't merge it with the master branch. One of the changes I made was to the favicons. I changed code here: `/website/frontend/templates/template.html` and I added a directory 'ico' here: `/static/images`

Wasn't sure if I made those changes in a way that would have broken the way Django is pulling together the static resources.

**Comment by awong-dev** [comment]
See the Django upgrade bug I filled.  I suspect got created a new heroku
app instead of using the one u had if you hit this problem. You can use the
command in there to work around things for now.

The right fix I think is to create a Digital44 GitHub org and transfer the
repo there. Will start on that toniHT.

**Comment by ezramechaber** [comment]
Yep, worked like a charm once I set the extra config to disable collectstatic. Will merge the changes back into the master branch.
